regions:
  - eu-west-1
  - us-east-1
  - global
  - eu-central-1

account-blocklist:
  - "123456789123"

accounts:
  "ACCOUNT_ID":
    filters:
      IAMUser:
        - type: "glob"
          value: "protected-*"
      IAMUserAccessKey:
        - type: "glob"
          value: "protected-* -> *"
      IAMUserPolicyAttachment:
        - type: "glob"
          value: "ci-user -> *"
        - type: "glob"
          value: "protected-* -> *"
      IAMPolicy:
        - type: "glob"
          value: "*/protected-*"
      IAMRole:
        - "OrganizationAccountAccessRole"
        - "OrganizationIAMRoleAccess"
        - type: "glob"
          value: "protected-*"
        - type: "glob"
          value: "cdk-*-role-*"
      IAMRolePolicyAttachment:
        - "OrganizationIAMRoleAccess -> IAMFullAccess"
        - type: "glob"
          value: "protected-* -> *"
        - type: "glob"
          value: "cdk-*-role-* -> *"
      IAMRolePolicy:
        - "OrganizationAccountAccessRole -> AdministratorAccess"
        - type: "glob"
          value: "protected-* -> *"
        - type: "glob"
          value: "cdk-*-role-* -> *"
      CloudTrailTrail:
        - type: "glob"
          value: "*"
      CodeBuildProject:
        - type: "glob"
          value: "protected-*"
      CloudWatchLogsLogGroup:
        - "/aws/codebuild/protected-aws-account-cleanup-runner"
      CloudFormationStack:
        - type: "glob"
          value: "protected-*"
        - "CDKToolkit"
      CloudWatchEventsRule:
        - type: "glob"
          value: "*protected-cleanup-trigger"
      S3Bucket:
        - type: "glob"
          value: "s3://persistent-*"
        - type: "glob"
          value: "s3://cdk-*-assets-*"
      OpsWorksUserProfile:
        - type: "glob"
          value: "arn:aws:sts::*:assumed-role/protected-*/*"
      SSMParameter:
        - type: "glob"
          value: "/cdk-bootstrap/*/version"
      CloudWatchEventsTarget:
        - type: "glob"
          value: "Rule: protected-*"
      ECRRepository:
        - type: "glob"
          value: "Repository: cdk-*-container-assets-*"
    resource-types:
      excludes:
        - S3Object
